name: 버그 리포트
description: 수정할 버그 작업용 템플릿
title: "[bug] "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: 🔧 수정 내용
      placeholder: 어떤 버그를 어떻게 수정할 예정인지 간단히 적어주세요.
    validations:
      required: true

